### ISSUE TITLE
Parameters do not get updated correctly when switching models

### ISSUE THREAD

**Issue by hongkheng** [Sonoport/jsmplayer#1]
The parameters of each models were not generated correctly when switching between models.

Since the player was loaded with Looper as the first model, the parameters for Looper were correct. But after switching to Trigger after Looper from the dropdown menu, the parameters generated were still the parameters for Looper instead.

**Comment by notthetup** [comment]
Thanks! Fixed with # 595a59.

**Comment by notthetup** [comment]
Thanks! Fixed with 595a59198f64db5ec
